# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [10]:
# Your code here
import numpy as np
A = np.zeros((3,3))
B = np.zeros((3,3))
C = np.zeros((3,3))


In [13]:
for i in range(0, A.shape[0]):
    for j in range(0, A.shape[1]):
        A[i][j] = np.random.randint(0,10)
        B[i][j] = np.random.randint(0,10)
        C[i][j] = np.random.randint(0,10)

In [15]:
A, B, C

(array([[6., 6., 0.],
        [9., 1., 5.],
        [1., 8., 0.]]), array([[8., 6., 5.],
        [1., 6., 3.],
        [7., 9., 4.]]), array([[5., 5., 6.],
        [0., 4., 9.],
        [7., 0., 3.]]))

In [20]:
np.dot(A, (B+C))

array([[ 84., 126., 138.],
       [188., 154., 146.],
       [ 21.,  91., 107.]])

In [22]:
np.dot(A,B) + np.dot(A,C)

array([[ 84., 126., 138.],
       [188., 154., 146.],
       [ 21.,  91., 107.]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [16]:
# Your code here 
np.dot(A, np.dot(B, C))

array([[ 606.,  558., 1116.],
       [1016.,  960., 1797.],
       [ 283.,  296.,  669.]])

In [19]:
np.dot(np.dot(A, B), C)

array([[ 606.,  558., 1116.],
       [1016.,  960., 1797.],
       [ 283.,  296.,  669.]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [24]:
# Your code here 
np.dot(A, B)

array([[ 54.,  72.,  48.],
       [108., 105.,  68.],
       [ 16.,  54.,  29.]])

In [25]:
np.dot(B, A)

array([[107.,  94.,  30.],
       [ 63.,  36.,  30.],
       [127.,  83.,  45.]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [4]:
# Your code here 

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [5]:
# Your code here 

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 